### ISSUE TITLE
Make it possible to follow traversals

### ISSUE THREAD

**Issue by sliekens** [zacanger/path-normalize#1]
The current behavior is to strip traversals (unless they are at the start of a path, apparently).

- `'./../foo'` -> `'./foo'`
- ` '../foo/../bar'` -> `'../foo/bar'`

I'm looking for a library that strips `.` and `..` if they are redundant but otherwise leaves it alone.

- convert `dirname/.` to `dirname`
- convert `./../` to `../`
- strip `dirname/..`

Example: `./../foo/./../bar` -> `../bar`

because `./../foo/./../bar` = `../foo/./../bar` = `../foo/../bar` = `../bar`

**Comment by zautumnz** [comment]
I actually wanted path traversal to be impossible with this lib. The fact that it works at the start of a path means there's a bug. I believe [this library](https://www.npmjs.com/package/normalize-path) allows path traversal. I think what you're looking for might be a `path.resolve` for the browser, though, not a `path.normalize`.

**Comment by sliekens** [comment]
I already tried normalize-path and they don't support it either.
https://github.com/jonschlinkert/normalize-path/issues/6

I'm not sure if a `resolve` is really what I need. I don't care if the path actually exists or not.

**Comment by sliekens** [comment]
What I was expecting to get from this library was an easy, although naive way to check if `a/b/c/` and `a/b/./c/` point to the same thing or not

**Comment by zautumnz** [comment]
That's what `path.resolve` does. Node's `path.resolve` doesn't check if a path actually exists, it just joins strings and resolves them to a path-like string. https://nodejs.org/api/path.html#path_path_resolve_paths

```[:~] $ node
> path.resolve('../../foo/bar')
'/foo/bar'
> [:~] $ ls / | grep foo
[:~] 1 $
```

**Comment by sliekens** [comment]
Too bad it always returns an absolute path. That's really not what I'm looking for.

```
path.resolve('wwwroot', 'static_files/png/', '../gif/image.gif');
// if the current working directory is /home/myself/node,
// this returns '/home/myself/node/wwwroot/static_files/gif/image.gif'
```

I still don't think I need a resolve function if that means converting the path to an absolute path.

I just want something that trims unnecessary symbols from a path string, but in a way that doesn't change the meaning of the path. I think that's what normalizing means.

> I actually wanted path traversal to be impossible with this lib.

For security reasons? I understand that. Can't you implement both behaviors and hide the insecure one behind a flag?

Full disclosure: I was planning to use this lib in a custom TSLint rule that automatically normalizes import statements. So security is a nonissue for where I'm going with this.

**Comment by zautumnz** [comment]
Oh! I understand what you're saying now, sorry.

Yeah, I could add an argument. `normalize(path, handleTraversal = true)`, so for your use case you could call `normalize(path, false)`.

**Comment by sliekens** [comment]
Would it still strip redundant traversals?
eg. `parent/./direct-child` would be normalized to `parent/direct-child` because the `./` is redundant

**Comment by zautumnz** [comment]
It seems like that would be expected behavior. Do you have bandwidth to put in a PR for this? If not, I can try to add that feature sometime this week.

**Comment by sliekens** [comment]
Maybe I can do it over the weekend but I'm not in a rush.

Besides I think more thought needs to go into what the rules should be for trimming leading dots and slashes. Most systems treat `'foo'` and `'./foo'` as relative paths but in TypeScript the former is an absolute path.

**Comment by wchargin** [comment]
Strong +1. I was very happy to find this library—no dependencies, has
Flow and TypeScript declarations, points to the source for the correct
Node function in the README, even notes that this is specifically the
POSIX version. But despite the fact that the package claims to be a
“browser-oriented `path.normalize`”, it does not perform the critical
normalization of `..`. To have `a/b/../c` resolve to `a/b/c` is
_extremely_ misleading. I can’t think of a situation in which that could
possibly be the correct behavior.

> Besides I think more thought needs to go into what the rules should be
> for trimming leading dots and slashes. Most systems treat `'foo'` and
> `'./foo'` as relative paths but in TypeScript the former is an
> absolute path.

If the goal of the package is to emulate `path.posix.normalize`, then
the semantics are clear: we use POSIX path semantics, and in particular
whatever Node does. For instance:

  - `./../foo/./../bar` becomes `../bar`, exactly as in @StevenLiekens’s
    example;
  - `parent/./direct-child` becomes `parent/direct-child`, exactly as in
    @zacanger’s example;
  - `./foo` becomes `foo`, which is equivalent on POSIX.

Those clients who want TypeScript semantics can accomodate this by
implementing the appropriate function:

```typescript
function tsNormalize(path: string) {
  const isRelative = path.charCodeAt(0) === 0x2e;
  const normal = require("path-normalize")(path);
  return isRelative ? "./" + normal : normal;
}
```

or whatever the TypeScript semantics happen to be. But it seems clear
that the TypeScript semantics should not drive the specification of this
package.

> Do you have bandwidth to put in a PR for this?

I can easily put in a PR that makes this module _actually_ the same as
Node’s `path.posix.normalize`, without adding any options or anything.
Would you like that? Please note that this would constitute a
backward-incompatible change, but in my opinion it is a bugfix and
should be merged.

**Comment by sliekens** [comment]
> To have a/b/../c resolve to a/b/c is
> extremely misleading. I can’t think of a situation in which that could
> possibly be the correct behavior.

It's a common practice in web servers to prevent [directory traversal attacks](https://en.wikipedia.org/wiki/Directory_traversal_attack). I'm guessing path-normalize does it for similar reasons. Maybe @zacanger can clarify why it is the way it is right now.

PS: thanks for referencing `path.posix.normalize`, I'm going to see if I can just use that instead.

**Comment by zautumnz** [comment]
@wchargin switching back to plain Node `path.normalize` behavior should be simple, I changed things in [this commit](https://github.com/zacanger/path-normalize/commit/232d23c4a3fff96c8e7848eeda2b6c38736eeb40). Yes, the idea was to prevent directory traversal, but as @StevenLiekens I didn't really do so all that well.

I'm open to just changing back to Node's behavior, the only reason I started stripping `..` is because I felt that it made more sense in a browser environment.

I don't really understand the TypeScript issue, because I don't use TypeScript. Is that different from Node's module resolution (as in, `require('foo')` means `foo` needs to either be a global or in `node_modules`)?

Either way, I'm happy to accept a PR changing back to Node's behavior, or I can make the change. Assuming nothing comes up, I can do it tomorrow night. According to npm, the only (published, public) dependent of this package is my own `react-router-path-normalize`, and I can strip dots that look like traversals there.

**Comment by sliekens** [comment]
TypeScript was just an example of a system where the rules for leading dots and slashes are different.

If the current dir is `/home/myself/node`:
- `import './foo'` resolves to `/home/myself/node/foo`
- `import 'foo'` resolves to `/home/myself/node/node_modules/foo`
- `import '/foo'` resolves to `/foo`

 But don't worry about that. Making path-normalize actually POSIX compliant is more than enough.

Oh and you can still detect directory traversal attacks outside path-normalize by checking if the normalized path starts with `../`.

**Comment by zautumnz** [comment]
@StevenLiekens @wchargin I reverted some commits. The diff is [here](https://github.com/zacanger/path-normalize/compare/v2.1.3...v3.0.0), and 3.0.0 is currently published on npm as `next` (so `npm i path-normalize@next`). I believe this gets this lib back to Node's `path.posix.normalize` behavior (plus a `decodeURIComponent`), though I want to dig into Node's code and see if they've made any changes/improvements.

**Comment by sliekens** [comment]
Nice but check your test cases because some of them look suspicious. One has a path segment that is `...`. And there are no test cases for `allowAboveRoot = true`.

**Comment by zautumnz** [comment]
Tests are updated. 3.0.2 is now latest, (instead of `next`) and essentially just restores the functionality of v0.4.2.

**Comment by sliekens** [comment]
Nice, thanks for the quick fix.
